# Generated by Django 5.2.10 on 2026-02-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=100)),
                ('lastLogin', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Active', max_length=50)),
            ],
        ),
    ]
