# Generated by Django 5.2.10 on 2026-03-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_users', '0002_systemuser_assignedstores_systemuser_createdat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='id',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False),
        ),
    ]
