# Generated by Django 5.2.12 on 2026-03-25 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0008_school_subscription_headteacher_fields'),
        ('admin_users', '0003_systemuser_password_alter_systemuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='admin_dashboard.school'),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='lastLogin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
