# Generated by Django 5.2.12 on 2026-03-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_distributions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notcollected',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
