# Generated by Django 5.2.12 on 2026-03-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_notcollected_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='nemis_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pathway',
            field=models.CharField(blank=True, choices=[('STEM', 'STEM'), ('Social Sciences', 'Social Sciences'), ('Arts and Sports Science', 'Arts and Sports Science')], max_length=50, null=True),
        ),
    ]
