# Generated by Django 6.0.4 on 2026-04-14 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_add_middle_name_nemis_pathway'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. FS-2025-CATB-01', max_length=255)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField()),
                ('student_category', models.CharField(choices=[('boarder', 'Boarder'), ('day_scholar', 'Day Scholar')], default='boarder', max_length=30)),
                ('term1_pct', models.IntegerField(default=50, help_text='Term 1 percentage')),
                ('term2_pct', models.IntegerField(default=30, help_text='Term 2 percentage')),
                ('term3_pct', models.IntegerField(default=20, help_text='Term 3 percentage')),
                ('is_active', models.BooleanField(default=True)),
                ('approved_by', models.CharField(blank=True, default='', max_length=255)),
                ('approval_ref', models.CharField(blank=True, default='', max_length=100)),
                ('allow_update', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='Bursary',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('bursary_ref', models.CharField(blank=True, default='', max_length=100)),
                ('bursary_type', models.CharField(choices=[('school_based', 'School-Based'), ('external', 'External')], max_length=20)),
                ('sponsor', models.CharField(max_length=255)),
                ('acknowledged_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('paid_to_student', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('received_as_fees', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('acknowledged', 'Acknowledged'), ('paid_to_student', 'Paid to Student'), ('received_as_fees', 'Received as Fees'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('narration', models.TextField(blank=True, default='')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bursaries', to='students.student')),
            ],
            options={
                'verbose_name_plural': 'bursaries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_head', models.CharField(max_length=255)),
                ('gok_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('parent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('annual_amount', models.DecimalField(decimal_places=2, default=0, help_text='Auto-computed: GOK + Parent', max_digits=14)),
                ('funding_type', models.CharField(choices=[('GOK', 'GOK'), ('Parent', 'Parent'), ('Mixed', 'Mixed')], default='Mixed', max_length=10)),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='students.feestructure')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StudentBill',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('bill_number', models.CharField(blank=True, default='', max_length=50)),
                ('term', models.CharField(choices=[('T1', 'Term 1'), ('T2', 'Term 2'), ('T3', 'Term 3')], max_length=5)),
                ('year', models.CharField(max_length=10)),
                ('bill_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='students.feestructure')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='students.student')),
            ],
            options={
                'ordering': ['-bill_date', '-created_at'],
                'unique_together': {('student', 'fee_structure', 'term')},
            },
        ),
        migrations.CreateModel(
            name='StudentBillLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_head', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='students.studentbill')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
