# Generated by Django 5.2.10 on 2026-02-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=100)),
                ('trend', models.CharField(max_length=100)),
                ('trendUp', models.BooleanField(default=True)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
    ]
