# Generated by Django 6.0.4 on 2026-04-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0008_school_subscription_headteacher_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
