# Generated by Django 6.0.4 on 2026-04-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0009_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='category',
            field=models.CharField(choices=[('day', 'Day School'), ('boarding_a', 'Boarding Category A*'), ('boarding_b', 'Boarding Category B*'), ('special_needs', 'Special Needs Boarding')], default='day', max_length=50),
        ),
    ]
