# Generated by Django 5.2.12 on 2026-03-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
