from django.urls import path
from .views import (
    InventoryListView,
    StoreItemListView,
    InventoryExportView,
    InventorySettingsView,
    DeliveriesListView, 
    DeliveryDetailView,
    DeliveryUpdateItemsView,
    DeliverySubmitDecisionView,
    DeliverySignDecisionView,
    DeliveryReminderView,
    LpoSendView,
    RequisitionsListView, 
    S12RequisitionListCreateView,
    S12RequisitionDetailView,
    IssueHistoryListView, 
    IssueStatsView,
    ReceivingHistoryListView,
    ReceivingStatsView,
    ReceivingHistoryDetailView,
    SupplierListView,
    SupplierDetailView,
    InventoryDetailView,
    LpoListCreateView,
    LpoStatsView,
    LpoDetailView,
    RequestersListView,
    RiaListCreateView,
    RiaDetailView,
    InventoryLedgerListView,
    StoreReportListView,
    StoreReportExportView,
    IPSASReportListView,
    IPSASReportExportView,
    ConsumablesLedgerListView,
    StockBalanceListView,
    StockBalanceExportView,
    DashboardTransactionsView,
    DashboardLowStockView,
    DashboardStatsView,
    StockAdjustmentListCreateView,
    StoreTransferListCreateView,
    FileMovementSettingsView,
    FileMovementListCreateView,
    FileMovementDetailView,
    RetentionRecordListCreateView,
    RetentionRecordDetailView,
    AppraisalWorkflowListCreateView,
    AppraisalWorkflowDetailView,
    DisposalRecordListCreateView,
    S2TransactionListView,
    S2TransactionDetailView,
    S2LedgerListView,
    S2LedgerDetailView,
    S2ReceiptView,
    S2IssueView,
    S2TransferView,
    S2ReturnView,
    S2DamageView,
    S2ReversalView,
    CapitalizationRuleListView,
    CapitalizationRuleDetailView,
    CapitalizationSettingView,
    CapitalizationPromptListView,
    CapitalizationPromptDetailView,
    ClassifyItemView,
    OverrideDecisionView,
    CapitalizationPendingPromptsView,
    BulkCapitalizationCreateView,
    BulkCapitalizationProcessView,
    FixedAssetListView,
    FixedAssetDetailView,
    FixedAssetStatusTransitionView,
    FixedAssetDisposalView,
    FixedAssetStatusHistoryView,
    FixedAssetMaintenanceListView,
    FixedAssetMaintenanceDetailView,
    FixedAssetStatsView,
)

urlpatterns = [
    path('settings/', InventorySettingsView.as_view(), name='storekeeper-inventory-settings'),
    path('inventory/export/', InventoryExportView.as_view(), name='storekeeper-inventory-export'),
    path('inventory/', InventoryListView.as_view(), name='storekeeper-inventory'),
    path('inventory/<str:id>/', InventoryDetailView.as_view(), name='storekeeper-inventory-detail'),
    path('inventory/<str:id>', InventoryDetailView.as_view(), name='storekeeper-inventory-detail'),
    path('deliveries/', DeliveriesListView.as_view(), name='storekeeper-deliveries'),
    path('deliveries/<str:id>/', DeliveryDetailView.as_view(), name='storekeeper-deliveries-detail'),
    path('deliveries/<str:id>/items/', DeliveryUpdateItemsView.as_view(), name='storekeeper-deliveries-items'),
    path('deliveries/<str:id>/decision/', DeliverySubmitDecisionView.as_view(), name='storekeeper-deliveries-decision'),
    path('deliveries/<str:pk>/sign/', DeliverySignDecisionView.as_view(), name='storekeeper-deliveries-sign'),
        path('deliveries/<str:id>/reminder/', DeliveryReminderView.as_view(), name='storekeeper-deliveries-reminder'),
    path('requisitions/', RequisitionsListView.as_view(), name='storekeeper-requisitions'),
    path('requesters/', RequestersListView.as_view(), name='storekeeper-requesters'),
    path('s12-requisitions/', S12RequisitionListCreateView.as_view(), name='storekeeper-s12-requisitions'),
    path('s12-requisitions/<str:id>/', S12RequisitionDetailView.as_view(), name='storekeeper-s12-requisitions-detail'),
    path('issue/', IssueHistoryListView.as_view(), name='storekeeper-issue-history'),
    path('issue/stats/', IssueStatsView.as_view(), name='storekeeper-issue-stats'),
    path('receive/', ReceivingHistoryListView.as_view(), name='storekeeper-receive-history'),
    path('receive/stats/', ReceivingStatsView.as_view(), name='storekeeper-receive-stats'),
    path('receive/<str:id>/', ReceivingHistoryDetailView.as_view(), name='storekeeper-receive-history-detail'),
    
    # New Missing Endpoints
    path('store-items', StoreItemListView.as_view(), name='storekeeper-store-items'),
    path('store-items/', StoreItemListView.as_view(), name='storekeeper-store-items-slash'),
    path('suppliers/', SupplierListView.as_view(), name='storekeeper-suppliers'),
    path('suppliers/<str:id>/', SupplierDetailView.as_view(), name='storekeeper-suppliers-detail'),
    path('lpos/', LpoListCreateView.as_view(), name='storekeeper-lpos'),
    path('lpos/stats/', LpoStatsView.as_view(), name='storekeeper-lpos-stats'),
    path('lpos/<str:id>/', LpoDetailView.as_view(), name='storekeeper-lpos-detail'),
    path('lpos/<str:id>/send/', LpoSendView.as_view(), name='storekeeper-lpos-send'),
    path('ria/', RiaListCreateView.as_view(), name='storekeeper-ria'),
    path('ria/<str:id>/', RiaDetailView.as_view(), name='storekeeper-ria-detail'),
    path('ledger/', InventoryLedgerListView.as_view(), name='storekeeper-ledger'),
    path('ledger/consumables', ConsumablesLedgerListView.as_view(), name='storekeeper-ledger-consumables'),
    path('stock-balances/', StockBalanceListView.as_view(), name='storekeeper-stock-balances'),
    path('stock-balances/export/', StockBalanceExportView.as_view(), name='storekeeper-stock-balances-export'),
    path('reports/', StoreReportListView.as_view(), name='storekeeper-reports'),
    path('reports/<str:id>/export/', StoreReportExportView.as_view(), name='storekeeper-reports-export'),
    path('reports/ipsas/', IPSASReportListView.as_view(), name='storekeeper-reports-ipsas'),
    path('reports/ipsas/<str:id>/export/', IPSASReportExportView.as_view(), name='storekeeper-reports-ipsas-export'),
    path('transfers/', StoreTransferListCreateView.as_view(), name='storekeeper-transfers'),
    path('records/movements/settings/', FileMovementSettingsView.as_view(), name='storekeeper-movements-settings'),
    path('records/movements/', FileMovementListCreateView.as_view(), name='storekeeper-movements'),
    path('records/movements/<str:id>/', FileMovementDetailView.as_view(), name='storekeeper-movements-detail'),
    path('records/retention/', RetentionRecordListCreateView.as_view(), name='storekeeper-retention'),
    path('records/retention/appraisals/', AppraisalWorkflowListCreateView.as_view(), name='storekeeper-retention-appraisals'),
    path('records/retention/appraisals/<str:id>/', AppraisalWorkflowDetailView.as_view(), name='storekeeper-retention-appraisals-detail'),
    path('records/retention/disposals/', DisposalRecordListCreateView.as_view(), name='storekeeper-retention-disposals'),
    path('records/retention/<str:id>/', RetentionRecordDetailView.as_view(), name='storekeeper-retention-detail'),
    path('adjustments/', StockAdjustmentListCreateView.as_view(), name='storekeeper-adjustments'),
    path('dashboard/transactions', DashboardTransactionsView.as_view(), name='storekeeper-dashboard-transactions'),
    path('dashboard/transactions/', DashboardTransactionsView.as_view(), name='storekeeper-dashboard-transactions-slash'),
    path('dashboard/low-stock', DashboardLowStockView.as_view(), name='storekeeper-dashboard-low-stock'),
    path('dashboard/low-stock/', DashboardLowStockView.as_view(), name='storekeeper-dashboard-low-stock-slash'),
    path('dashboard/stats', DashboardStatsView.as_view(), name='storekeeper-dashboard-stats'),
    path('dashboard/stats/', DashboardStatsView.as_view(), name='storekeeper-dashboard-stats-slash'),

    # Phase 2 — S2 Ledger & Core Stores Workflows
    path('s2/transactions/', S2TransactionListView.as_view(), name='storekeeper-s2-transactions'),
    path('s2/transactions/<str:id>/', S2TransactionDetailView.as_view(), name='storekeeper-s2-transactions-detail'),
    path('s2/ledger/', S2LedgerListView.as_view(), name='storekeeper-s2-ledger'),
    path('s2/ledger/<str:itemCode>/', S2LedgerDetailView.as_view(), name='storekeeper-s2-ledger-detail'),
    path('s2/receipt/', S2ReceiptView.as_view(), name='storekeeper-s2-receipt'),
    path('s2/issue/', S2IssueView.as_view(), name='storekeeper-s2-issue'),
    path('s2/transfer/', S2TransferView.as_view(), name='storekeeper-s2-transfer'),
    path('s2/return/', S2ReturnView.as_view(), name='storekeeper-s2-return'),
    path('s2/damage/', S2DamageView.as_view(), name='storekeeper-s2-damage'),
    path('s2/reverse/', S2ReversalView.as_view(), name='storekeeper-s2-reverse'),

    # Phase 3 — Capitalization Rules Engine & Decision Assistant
    path('capitalization/rules/', CapitalizationRuleListView.as_view(), name='storekeeper-cap-rules'),
    path('capitalization/rules/<int:id>/', CapitalizationRuleDetailView.as_view(), name='storekeeper-cap-rules-detail'),
    path('capitalization/settings/', CapitalizationSettingView.as_view(), name='storekeeper-cap-settings'),
    path('capitalization/prompts/', CapitalizationPromptListView.as_view(), name='storekeeper-cap-prompts'),
    path('capitalization/prompts/pending/', CapitalizationPendingPromptsView.as_view(), name='storekeeper-cap-prompts-pending'),
    path('capitalization/prompts/<str:id>/', CapitalizationPromptDetailView.as_view(), name='storekeeper-cap-prompts-detail'),
    path('capitalization/classify/', ClassifyItemView.as_view(), name='storekeeper-cap-classify'),
    path('capitalization/override/', OverrideDecisionView.as_view(), name='storekeeper-cap-override'),
    path('capitalization/bulk/', BulkCapitalizationCreateView.as_view(), name='storekeeper-cap-bulk'),
    path('capitalization/bulk/process/', BulkCapitalizationProcessView.as_view(), name='storekeeper-cap-bulk-process'),

    # Phase 4 — Fixed Asset Register & Lifecycle Management
    path('assets/stats/', FixedAssetStatsView.as_view(), name='storekeeper-assets-stats'),
    path('assets/', FixedAssetListView.as_view(), name='storekeeper-assets'),
    path('assets/<str:id>/', FixedAssetDetailView.as_view(), name='storekeeper-assets-detail'),
    path('assets/<str:id>/transition/', FixedAssetStatusTransitionView.as_view(), name='storekeeper-assets-transition'),
    path('assets/<str:id>/dispose/', FixedAssetDisposalView.as_view(), name='storekeeper-assets-dispose'),
    path('assets/<str:asset_id>/history/', FixedAssetStatusHistoryView.as_view(), name='storekeeper-assets-history'),
    path('assets/<str:asset_id>/maintenance/', FixedAssetMaintenanceListView.as_view(), name='storekeeper-assets-maintenance'),
    path('assets/<str:asset_id>/maintenance/<int:pk>/', FixedAssetMaintenanceDetailView.as_view(), name='storekeeper-assets-maintenance-detail'),
]
