from django.urls import path
from .views import (
    InventoryListView,
    StoreItemListView,
    InventoryExportView,
    InventorySettingsView,
    DeliveriesListView, 
    DeliveryDetailView,
    DeliveryUpdateItemsView,
    DeliverySubmitDecisionView,
    DeliverySignDecisionView,
    DeliveryReminderView,
    LpoSendView,
    RequisitionsListView, 
    S12RequisitionListCreateView,
    S12RequisitionDetailView,
    IssueHistoryListView, 
    IssueStatsView,
    ReceivingHistoryListView,
    ReceivingStatsView,
    ReceivingHistoryDetailView,
    SupplierListView,
    SupplierDetailView,
    InventoryDetailView,
    LpoListCreateView,
    LpoStatsView,
    LpoDetailView,
    RequestersListView,
    RiaListCreateView,
    RiaDetailView,
    InventoryLedgerListView,
    StoreReportListView,
    StoreReportExportView,
    ConsumablesLedgerListView,
    StockBalanceListView,
    StockBalanceExportView,
    DashboardTransactionsView,
    DashboardLowStockView,
    DashboardStatsView,
    StockAdjustmentListCreateView,
    StoreTransferListCreateView,
    FileMovementSettingsView,
    FileMovementListCreateView,
    FileMovementDetailView,
    RetentionRecordListCreateView,
    RetentionRecordDetailView,
    AppraisalWorkflowListCreateView,
    AppraisalWorkflowDetailView,
    DisposalRecordListCreateView
)

urlpatterns = [
    path('settings/', InventorySettingsView.as_view(), name='storekeeper-inventory-settings'),
    path('inventory/export/', InventoryExportView.as_view(), name='storekeeper-inventory-export'),
    path('inventory/', InventoryListView.as_view(), name='storekeeper-inventory'),
    path('inventory/<str:id>/', InventoryDetailView.as_view(), name='storekeeper-inventory-detail'),
    path('inventory/<str:id>', InventoryDetailView.as_view(), name='storekeeper-inventory-detail'),
    path('deliveries/', DeliveriesListView.as_view(), name='storekeeper-deliveries'),
    path('deliveries/<str:id>/', DeliveryDetailView.as_view(), name='storekeeper-deliveries-detail'),
    path('deliveries/<str:id>/items/', DeliveryUpdateItemsView.as_view(), name='storekeeper-deliveries-items'),
    path('deliveries/<str:id>/decision/', DeliverySubmitDecisionView.as_view(), name='storekeeper-deliveries-decision'),
    path('deliveries/<str:pk>/sign/', DeliverySignDecisionView.as_view(), name='storekeeper-deliveries-sign'),
        path('deliveries/<str:id>/reminder/', DeliveryReminderView.as_view(), name='storekeeper-deliveries-reminder'),
    path('requisitions/', RequisitionsListView.as_view(), name='storekeeper-requisitions'),
    path('requesters/', RequestersListView.as_view(), name='storekeeper-requesters'),
    path('s12-requisitions/', S12RequisitionListCreateView.as_view(), name='storekeeper-s12-requisitions'),
    path('s12-requisitions/<str:id>/', S12RequisitionDetailView.as_view(), name='storekeeper-s12-requisitions-detail'),
    path('issue/', IssueHistoryListView.as_view(), name='storekeeper-issue-history'),
    path('issue/stats/', IssueStatsView.as_view(), name='storekeeper-issue-stats'),
    path('receive/', ReceivingHistoryListView.as_view(), name='storekeeper-receive-history'),
    path('receive/stats/', ReceivingStatsView.as_view(), name='storekeeper-receive-stats'),
    path('receive/<str:id>/', ReceivingHistoryDetailView.as_view(), name='storekeeper-receive-history-detail'),
    
    # New Missing Endpoints
    path('store-items', StoreItemListView.as_view(), name='storekeeper-store-items'),
    path('store-items/', StoreItemListView.as_view(), name='storekeeper-store-items-slash'),
    path('suppliers/', SupplierListView.as_view(), name='storekeeper-suppliers'),
    path('suppliers/<str:id>/', SupplierDetailView.as_view(), name='storekeeper-suppliers-detail'),
    path('lpos/', LpoListCreateView.as_view(), name='storekeeper-lpos'),
    path('lpos/stats/', LpoStatsView.as_view(), name='storekeeper-lpos-stats'),
    path('lpos/<str:id>/', LpoDetailView.as_view(), name='storekeeper-lpos-detail'),
    path('lpos/<str:id>/send/', LpoSendView.as_view(), name='storekeeper-lpos-send'),
    path('ria/', RiaListCreateView.as_view(), name='storekeeper-ria'),
    path('ria/<str:id>/', RiaDetailView.as_view(), name='storekeeper-ria-detail'),
    path('ledger/', InventoryLedgerListView.as_view(), name='storekeeper-ledger'),
    path('ledger/consumables', ConsumablesLedgerListView.as_view(), name='storekeeper-ledger-consumables'),
    path('stock-balances/', StockBalanceListView.as_view(), name='storekeeper-stock-balances'),
    path('stock-balances/export/', StockBalanceExportView.as_view(), name='storekeeper-stock-balances-export'),
    path('reports/', StoreReportListView.as_view(), name='storekeeper-reports'),
    path('reports/<str:id>/export/', StoreReportExportView.as_view(), name='storekeeper-reports-export'),
    path('transfers/', StoreTransferListCreateView.as_view(), name='storekeeper-transfers'),
    path('records/movements/settings/', FileMovementSettingsView.as_view(), name='storekeeper-movements-settings'),
    path('records/movements/', FileMovementListCreateView.as_view(), name='storekeeper-movements'),
    path('records/movements/<str:id>/', FileMovementDetailView.as_view(), name='storekeeper-movements-detail'),
    path('records/retention/', RetentionRecordListCreateView.as_view(), name='storekeeper-retention'),
    path('records/retention/appraisals/', AppraisalWorkflowListCreateView.as_view(), name='storekeeper-retention-appraisals'),
    path('records/retention/appraisals/<str:id>/', AppraisalWorkflowDetailView.as_view(), name='storekeeper-retention-appraisals-detail'),
    path('records/retention/disposals/', DisposalRecordListCreateView.as_view(), name='storekeeper-retention-disposals'),
    path('records/retention/<str:id>/', RetentionRecordDetailView.as_view(), name='storekeeper-retention-detail'),
    path('adjustments/', StockAdjustmentListCreateView.as_view(), name='storekeeper-adjustments'),
    path('dashboard/transactions', DashboardTransactionsView.as_view(), name='storekeeper-dashboard-transactions'),
    path('dashboard/transactions/', DashboardTransactionsView.as_view(), name='storekeeper-dashboard-transactions-slash'),
    path('dashboard/low-stock', DashboardLowStockView.as_view(), name='storekeeper-dashboard-low-stock'),
    path('dashboard/low-stock/', DashboardLowStockView.as_view(), name='storekeeper-dashboard-low-stock-slash'),
    path('dashboard/stats', DashboardStatsView.as_view(), name='storekeeper-dashboard-stats'),
    path('dashboard/stats/', DashboardStatsView.as_view(), name='storekeeper-dashboard-stats-slash'),
]
