# Generated by Django 6.0.4 on 2026-04-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='lpo_lso_number',
            field=models.CharField(blank=True, default='', help_text='Local Purchase Order / Local Service Order reference', max_length=100),
        ),
    ]
