# Generated by Django 5.2.10 on 2026-02-26 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('deliveryId', models.CharField(max_length=100)),
                ('dateTime', models.DateTimeField()),
                ('supplierName', models.CharField(max_length=255)),
                ('lpoReference', models.CharField(max_length=100)),
                ('deliveryPerson', models.CharField(max_length=100)),
                ('vehicleNumber', models.CharField(max_length=50)),
                ('deliveryNote', models.CharField(max_length=100)),
                ('packages', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=255)),
                ('receivedBy', models.CharField(max_length=100)),
                ('receivedAt', models.DateTimeField()),
                ('storageLocation', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('signatures', models.JSONField(default=list)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('assetType', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('minimumStockLevel', models.IntegerField(default=0)),
                ('reorderLevel', models.IntegerField(default=0)),
                ('openingBalance', models.IntegerField(default=0)),
                ('hasBeenUsed', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('lastUpdated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IssueHistory',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('department', models.CharField(max_length=255)),
                ('requestedBy', models.CharField(max_length=255)),
                ('items', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReceivingHistory',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('sourceType', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=255)),
                ('storeLocation', models.CharField(max_length=100)),
                ('items', models.IntegerField()),
                ('totalValue', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('storekeeperSignature', models.CharField(max_length=100)),
                ('signedAt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('s12Number', models.CharField(max_length=100)),
                ('requestDate', models.DateField()),
                ('requestingDepartment', models.CharField(max_length=255)),
                ('requestedBy', models.CharField(max_length=255)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=100)),
                ('receiverSignature', models.BooleanField(default=False)),
                ('issuerSignature', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionItem',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=50)),
                ('quantityRequested', models.IntegerField(default=0)),
                ('quantityApproved', models.IntegerField(default=0)),
                ('quantityIssued', models.IntegerField(default=0)),
                ('unitPrice', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('itemCode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stores.inventoryitem')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stores.requisition')),
            ],
        ),
    ]
