# Generated by Django 5.2.10 on 2026-02-26 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLedger',
            fields=[
                ('itemCode', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=50)),
                ('openingQty', models.IntegerField(default=0)),
                ('openingValue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('totalReceiptsQty', models.IntegerField(default=0)),
                ('totalReceiptsValue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('totalIssuesQty', models.IntegerField(default=0)),
                ('totalIssuesValue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closingQty', models.IntegerField(default=0)),
                ('closingValue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('lpoNumber', models.CharField(max_length=100)),
                ('supplierName', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RoutineIssueAuthority',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=255)),
                ('costCenter', models.CharField(max_length=100)),
                ('responsibleOfficer', models.CharField(max_length=255)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreReport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(max_length=100)),
                ('iconName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('taxPin', models.CharField(max_length=50)),
                ('contactPerson', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='receivinghistory',
            name='signedAt',
        ),
        migrations.RemoveField(
            model_name='receivinghistory',
            name='status',
        ),
        migrations.RemoveField(
            model_name='receivinghistory',
            name='storekeeperSignature',
        ),
        migrations.CreateModel(
            name='LedgerIssue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('s13No', models.CharField(max_length=100)),
                ('qty', models.IntegerField(default=0)),
                ('dept', models.CharField(max_length=255)),
                ('unitCost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('totalCost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('riaNo', models.CharField(blank=True, max_length=100, null=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='stores.inventoryledger')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerReceipt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('grnNo', models.CharField(max_length=100)),
                ('qty', models.IntegerField(default=0)),
                ('unitCost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('totalCost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='stores.inventoryledger')),
            ],
        ),
        migrations.CreateModel(
            name='RiaItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('itemCode', models.CharField(max_length=100)),
                ('itemName', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=50)),
                ('approvedQty', models.IntegerField(default=0)),
                ('usedQty', models.IntegerField(default=0)),
                ('ria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stores.routineissueauthority')),
            ],
        ),
    ]
