# Generated by Django 5.2.10 on 2026-02-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_inventoryledger_purchaseorder_routineissueauthority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivinghistory',
            name='signedAt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receivinghistory',
            name='status',
            field=models.CharField(default='Posted', max_length=100),
        ),
        migrations.AddField(
            model_name='receivinghistory',
            name='storekeeperSignature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
