# Generated by Django 5.2.10 on 2026-02-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_purchaseorder_createdat_purchaseorder_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storereport',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='storereport',
            name='iconName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='storereport',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='storereport',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
