# Generated by Django 5.2.10 on 2026-03-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_storereport_date_alter_storereport_iconname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='expiryDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='id',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False),
        ),
    ]
