# Generated by Django 5.2.10 on 2026-03-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_inventoryitem_expirydate_alter_inventoryitem_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySetting',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.JSONField(default=list)),
            ],
        ),
    ]
