# Generated by Django 5.2.10 on 2026-03-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_inventorysetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
