# Generated by Django 5.2.10 on 2026-03-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_inventoryitem_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivinghistory',
            name='totalValue',
        ),
        migrations.AddField(
            model_name='receivinghistory',
            name='amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='issuehistory',
            name='id',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='issuehistory',
            name='items',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='receivinghistory',
            name='id',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='receivinghistory',
            name='items',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
