# Generated by Django 5.2.10 on 2026-03-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_remove_receivinghistory_totalvalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuehistory',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
