# Generated by Django 5.2.10 on 2026-03-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_issuehistory_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivinghistory',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
