# Generated by Django 5.2.10 on 2026-03-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_receivinghistory_createdat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='remarks',
            new_name='overallRemarks',
        ),
        migrations.AddField(
            model_name='delivery',
            name='decision',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='grnGenerated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='delivery',
            name='grnId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='inspectionCompletedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='items',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='delivery',
            name='lpoId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='createdAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='dateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='receivedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='updatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
