# Generated by Django 5.2.10 on 2026-03-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_rename_remarks_delivery_overallremarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='approvedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approvedBy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='linkedGRNs',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='preparedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='requisitionRef',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
