# Generated by Django 5.2.10 on 2026-03-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0013_purchaseorder_approvedat_purchaseorder_approvedby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='supplierId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
