# Generated by Django 5.2.10 on 2026-03-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0014_delivery_supplierid_alter_delivery_createdat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('qty', models.IntegerField(default=0)),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('approvedBy', models.CharField(default='-', max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
