# Generated by Django 5.2.10 on 2026-03-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0015_stockadjustment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreTransfer',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=100)),
                ('from_store', models.CharField(max_length=255)),
                ('to_store', models.CharField(max_length=255)),
                ('items', models.IntegerField(default=0)),
                ('status', models.CharField(default='Pending Approval', max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
