# Generated by Django 5.2.10 on 2026-03-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_storetransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMovement',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('fileReference', models.CharField(max_length=255)),
                ('fileTitle', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('borrowedBy', models.CharField(max_length=255)),
                ('borrowerDepartment', models.CharField(max_length=100)),
                ('borrowDate', models.CharField(max_length=100)),
                ('expectedReturnDate', models.CharField(max_length=100)),
                ('actualReturnDate', models.CharField(blank=True, max_length=100, null=True)),
                ('purpose', models.CharField(max_length=255)),
                ('status', models.CharField(default='Checked Out', max_length=50)),
                ('borrowerSignature', models.BooleanField(default=False)),
                ('returnSignature', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
