# Generated by Django 5.2.10 on 2026-03-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0017_filemovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalWorkflow',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('recordId', models.CharField(max_length=50)),
                ('recordCode', models.CharField(max_length=255)),
                ('recordTitle', models.CharField(max_length=255)),
                ('initiatedBy', models.CharField(max_length=100)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisposalRecord',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('recordId', models.CharField(max_length=50)),
                ('appraisalId', models.CharField(max_length=50)),
                ('disposalMethod', models.CharField(max_length=100)),
                ('certificateNumber', models.CharField(blank=True, max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RetentionRecord',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('recordCode', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('creationDate', models.DateField()),
                ('retentionYears', models.IntegerField(default=7)),
                ('expiryDate', models.DateField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('custodian', models.CharField(max_length=100)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
