# Generated by Django 5.2.10 on 2026-03-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0018_appraisalworkflow_disposalrecord_retentionrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('department', models.CharField(max_length=255)),
                ('requestedBy', models.CharField(max_length=255)),
                ('items', models.IntegerField(default=0)),
                ('estimatedValue', models.CharField(max_length=100)),
                ('status', models.CharField(default='draft', max_length=50)),
                ('priority', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('justification', models.TextField()),
                ('budgetCode', models.CharField(max_length=100)),
                ('approvedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('approvedDate', models.DateField(blank=True, null=True)),
                ('rejectionReason', models.TextField(blank=True, null=True)),
                ('processedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('processedDate', models.DateField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
