# Generated by Django 5.2.10 on 2026-03-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0019_purchaserequisition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('vendor', models.CharField(max_length=255)),
                ('submittedDate', models.DateField()),
                ('value', models.CharField(max_length=100)),
                ('validUntil', models.DateField()),
                ('status', models.CharField(default='pending_review', max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('budget', models.CharField(max_length=100)),
                ('closingDate', models.DateField()),
                ('bids', models.IntegerField(default=0)),
                ('status', models.CharField(default='open', max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
