# Generated by Django 5.2.10 on 2026-03-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0020_quotation_tender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementReference',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('referenceNumber', models.CharField(max_length=100)),
                ('entityCode', models.CharField(max_length=50)),
                ('procurementType', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('department', models.CharField(max_length=100)),
                ('requestedBy', models.CharField(max_length=255)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
