# Generated by Django 5.2.10 on 2026-03-09 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0021_procurementreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementContract',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('contractNumber', models.CharField(max_length=100)),
                ('contractName', models.CharField(max_length=255)),
                ('contractType', models.CharField(max_length=100)),
                ('contractorName', models.CharField(max_length=255)),
                ('totalValue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContractMilestone',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('dueDate', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('paidDate', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentMilestones', to='stores.procurementcontract')),
            ],
        ),
    ]
