# Generated by Django 6.0.3 on 2026-03-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0022_procurementcontract_contractmilestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementcontract',
            name='accountCharged',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='procurementcontract',
            name='actualCompletionDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procurementcontract',
            name='awardDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procurementcontract',
            name='commencementDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procurementcontract',
            name='completionDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procurementcontract',
            name='contractorAddress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='procurementcontract',
            name='contractorContact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='procurementcontract',
            name='createdBy',
            field=models.CharField(blank=True, default='Unknown', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='procurementcontract',
            name='guaranteeExpiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procurementcontract',
            name='performanceGuarantee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='procurementcontract',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procurementcontract',
            name='tenderReference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='procurementcontract',
            name='contractNumber',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
