# Generated by Django 5.2.12 on 2026-03-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0023_procurementcontract_accountcharged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerissue',
            name='balanceInStock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ledgerissue',
            name='requisitionNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ledgerissue',
            name='signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgerreceipt',
            name='balanceInStock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ledgerreceipt',
            name='requisitionNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ledgerreceipt',
            name='signatures',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledgerreceipt',
            name='supplierName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
