# Generated by Django 5.2.12 on 2026-04-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0024_ledgerissue_balanceinstock_ledgerissue_requisitionno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='S2LedgerEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('refNo', models.CharField(max_length=100)),
                ('txnType', models.CharField(choices=[('RECEIPT', 'Receipt'), ('ISSUE', 'Issue'), ('TRANSFER', 'Transfer'), ('RETURN', 'Return'), ('DAMAGE_LOSS', 'Damage / Loss')], max_length=20)),
                ('itemCode', models.CharField(max_length=100)),
                ('itemName', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('qtyReceived', models.IntegerField(default=0)),
                ('qtyIssued', models.IntegerField(default=0)),
                ('runningBalance', models.IntegerField(default=0)),
                ('unitCost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('totalValue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('supplier', models.CharField(blank=True, default='', max_length=255)),
                ('recipient', models.CharField(blank=True, default='', max_length=255)),
                ('department', models.CharField(blank=True, default='', max_length=255)),
                ('fromDept', models.CharField(blank=True, default='', max_length=255)),
                ('toDept', models.CharField(blank=True, default='', max_length=255)),
                ('lossReason', models.CharField(blank=True, choices=[('DAMAGED', 'Damaged'), ('LOST', 'Lost'), ('OBSOLETE', 'Obsolete'), ('CONDEMNED', 'Condemned')], default='', max_length=20)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost'), ('OBSOLETE', 'Obsolete'), ('CONDEMNED', 'Condemned')], default='GOOD', max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('createdBy', models.CharField(blank=True, default='', max_length=255)),
                ('approvedBy', models.CharField(blank=True, default='', max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date', 'id'],
                'indexes': [models.Index(fields=['itemCode'], name='stores_s2le_itemCod_b271eb_idx'), models.Index(fields=['txnType'], name='stores_s2le_txnType_64e966_idx'), models.Index(fields=['date'], name='stores_s2le_date_30a0de_idx')],
            },
        ),
    ]
