# Generated by Django 5.2.13 on 2026-05-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0026_delete_s2ledgerentry_inventoryledger_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalizationRule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('categoryType', models.CharField(choices=[('consumable', 'Consumable'), ('expendable', 'Expendable'), ('permanent', 'Permanent'), ('fixed_asset', 'Fixed Asset')], default='fixed_asset', help_text='Item type this rule applies to', max_length=20)),
                ('minCost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('minUsefulLifeMonths', models.IntegerField(default=12)),
                ('description', models.TextField(blank=True, default='')),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Capitalization Rule',
                'verbose_name_plural': 'Capitalization Rules',
                'db_table': 'stores_capitalization_rule',
            },
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('assetCode', models.CharField(blank=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('purchaseDate', models.DateField(blank=True, null=True)),
                ('purchaseCost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currentValue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('custodian', models.CharField(blank=True, default='', max_length=255)),
                ('usefulLifeMonths', models.IntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fixed Asset',
                'verbose_name_plural': 'Fixed Assets',
                'db_table': 'stores_fixed_asset',
            },
        ),
        migrations.CreateModel(
            name='LsoRecord',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('lsoNumber', models.CharField(blank=True, max_length=100, unique=True)),
                ('orderType', models.CharField(choices=[('lso', 'Local Service Order'), ('lpo', 'Local Purchase Order')], default='lpo', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('supplierName', models.CharField(blank=True, default='', max_length=255)),
                ('totalValue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(default='draft', max_length=50)),
                ('createdBy', models.CharField(blank=True, default='', max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LSO/LPO Record',
                'verbose_name_plural': 'LSO/LPO Records',
                'db_table': 'stores_lso_record',
            },
        ),
        migrations.CreateModel(
            name='S2Ledger',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('itemCode', models.CharField(db_index=True, max_length=100)),
                ('itemName', models.CharField(blank=True, default='', max_length=255)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('openingBalance', models.IntegerField(default=0)),
                ('receiptsQty', models.IntegerField(default=0)),
                ('receiptsValue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('issuesQty', models.IntegerField(default=0)),
                ('issuesValue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('closingBalance', models.IntegerField(default=0)),
                ('closingValue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'S2 Ledger',
                'verbose_name_plural': 'S2 Ledgers',
                'db_table': 'stores_s2_ledger',
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='category_type',
            field=models.CharField(choices=[('consumable', 'Consumable'), ('expendable', 'Expendable'), ('permanent', 'Permanent'), ('fixed_asset', 'Fixed Asset')], default='consumable', help_text='Classification type: consumable, expendable, permanent, or fixed_asset', max_length=20),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='default_custodian_required',
            field=models.BooleanField(blank=True, default=False, help_text='Whether a custodian assignment is required for this item'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='min_useful_life',
            field=models.IntegerField(blank=True, default=0, help_text='Minimum useful life in months (for permanent/fixed_asset items)'),
        ),
    ]
