# Generated by Django 5.2.13 on 2026-05-06 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0027_phase1_foundation_data_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='s2ledger',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='s2ledger',
            name='category_type',
            field=models.CharField(blank=True, choices=[('consumable', 'Consumable'), ('expendable', 'Expendable'), ('permanent', 'Permanent'), ('fixed_asset', 'Fixed Asset')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='s2ledger',
            name='damagesQty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='s2ledger',
            name='damagesValue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='s2ledger',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='s2_ledgers', to='stores.inventoryitem'),
        ),
        migrations.AddField(
            model_name='s2ledger',
            name='lastTransactionDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='s2ledger',
            name='returnsQty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='s2ledger',
            name='returnsValue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='s2ledger',
            name='transfersInQty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='s2ledger',
            name='transfersInValue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='s2ledger',
            name='transfersOutQty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='s2ledger',
            name='transfersOutValue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='s2ledger',
            name='itemCode',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='S2Transaction',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('receipt', 'Receipt (GRN → Store)'), ('issue', 'Issue (Store → Dept)'), ('transfer', 'Department Transfer'), ('return', 'Return to Store'), ('damage', 'Damage / Loss'), ('condemn', 'Condemn / Write-off'), ('adjustment', 'Stock Adjustment')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('reversed', 'Reversed'), ('locked', 'Audit Locked')], db_index=True, default='posted', max_length=20)),
                ('ref_no', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('date', models.DateField(db_index=True)),
                ('item_code', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('item_name', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('category_type', models.CharField(blank=True, choices=[('consumable', 'Consumable'), ('expendable', 'Expendable'), ('permanent', 'Permanent'), ('fixed_asset', 'Fixed Asset')], default='', max_length=20)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('qty_received', models.IntegerField(default=0)),
                ('qty_issued', models.IntegerField(default=0)),
                ('running_balance_before', models.IntegerField(default=0)),
                ('running_balance_after', models.IntegerField(default=0)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('supplier_id', models.CharField(blank=True, default='', max_length=100)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=255)),
                ('custodian_id', models.CharField(blank=True, default='', max_length=100)),
                ('custodian_name', models.CharField(blank=True, default='', max_length=255)),
                ('dept_id', models.CharField(blank=True, default='', max_length=100)),
                ('dept_name', models.CharField(blank=True, default='', max_length=255)),
                ('condition', models.CharField(blank=True, default='', max_length=100)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('approved_by', models.CharField(blank=True, default='', max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True, default='')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='s2_transactions', to='stores.inventoryitem')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_entries', to='stores.s2transaction')),
            ],
            options={
                'verbose_name': 'S2 Transaction',
                'verbose_name_plural': 'S2 Transactions',
                'db_table': 'stores_s2_transaction',
                'ordering': ['-date', '-createdAt'],
            },
        ),
    ]
