# Generated by Django 5.2.13 on 2026-05-06 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0028_phase2_s2_ledger_workflows'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalizationSetting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('threshold', models.DecimalField(decimal_places=2, default=50000, help_text='Default capitalization threshold in KES', max_digits=12)),
                ('bulk_materiality', models.DecimalField(decimal_places=2, default=100000, help_text='Bulk/grouped materiality threshold in KES', max_digits=12)),
                ('min_useful_life', models.IntegerField(default=12, help_text='Default minimum useful life in months for capitalization')),
                ('depreciation_start_rule', models.CharField(choices=[('date_of_acquisition', 'Date of Acquisition'), ('month_after_acquisition', 'Month After Acquisition'), ('quarter_after_acquisition', 'Quarter After Acquisition')], default='month_after_acquisition', help_text='When depreciation begins', max_length=30)),
                ('default_residual_pct', models.DecimalField(decimal_places=2, default=10.0, help_text='Default residual value as percentage of cost', max_digits=5)),
                ('asset_classes', models.JSONField(blank=True, default=list, help_text='List of asset class definitions as JSON')),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Capitalization Setting',
                'verbose_name_plural': 'Capitalization Settings',
                'db_table': 'stores_capitalization_setting',
            },
        ),
        migrations.AlterModelOptions(
            name='capitalizationrule',
            options={'ordering': ['priority', 'id'], 'verbose_name': 'Capitalization Rule', 'verbose_name_plural': 'Capitalization Rules'},
        ),
        migrations.AddField(
            model_name='capitalizationrule',
            name='action',
            field=models.CharField(choices=[('expense', 'Expense Immediately'), ('capitalize', 'Capitalize as Asset'), ('prompt', 'Prompt for Decision')], default='expense', help_text='Action to take when rule matches', max_length=30),
        ),
        migrations.AddField(
            model_name='capitalizationrule',
            name='bulkMateriality',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total value threshold for bulk materiality', max_digits=12),
        ),
        migrations.AddField(
            model_name='capitalizationrule',
            name='bulkThreshold',
            field=models.IntegerField(default=1, help_text='Quantity threshold for bulk/grouped treatment (Rule D)'),
        ),
        migrations.AddField(
            model_name='capitalizationrule',
            name='priority',
            field=models.IntegerField(default=0, help_text='Evaluation priority (lower = evaluated first)'),
        ),
        migrations.AddField(
            model_name='capitalizationrule',
            name='rule_code',
            field=models.CharField(blank=True, help_text='Rule identifier: A, B, C, or D', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='capitalizationrule',
            name='rule_label',
            field=models.CharField(blank=True, default='', help_text='Human-readable rule description', max_length=100),
        ),
        migrations.AlterField(
            model_name='capitalizationrule',
            name='minCost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum unit cost to trigger capitalization', max_digits=12),
        ),
        migrations.AlterField(
            model_name='capitalizationrule',
            name='minUsefulLifeMonths',
            field=models.IntegerField(default=12, help_text='Minimum useful life in months'),
        ),
        migrations.CreateModel(
            name='CapitalizationPrompt',
            fields=[
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('item_code', models.CharField(blank=True, default='', max_length=100)),
                ('item_name', models.CharField(blank=True, default='', max_length=255)),
                ('category_type', models.CharField(blank=True, choices=[('consumable', 'Consumable'), ('expendable', 'Expendable'), ('permanent', 'Permanent'), ('fixed_asset', 'Fixed Asset')], default='', max_length=20)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity', models.IntegerField(default=1)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('applied_rule', models.CharField(blank=True, default='', max_length=10)),
                ('suggested_action', models.CharField(blank=True, choices=[('expense', 'Expense Immediately'), ('capitalize', 'Capitalize as Asset'), ('bulk_capitalize', 'Bulk/Grouped Capitalize'), ('prompt', 'Awaiting Decision')], default='', max_length=30)),
                ('suggested_category_type', models.CharField(blank=True, default='', help_text='Auto-suggested category type', max_length=20)),
                ('override_decision', models.CharField(blank=True, choices=[('', 'No Override'), ('expense', 'Override → Expense'), ('capitalize', 'Override → Capitalize'), ('reclassify', 'Override → Reclassify')], default='', max_length=30)),
                ('override_reason', models.TextField(blank=True, default='')),
                ('override_by', models.CharField(blank=True, default='', max_length=255)),
                ('override_at', models.DateTimeField(blank=True, null=True)),
                ('approval_status', models.CharField(choices=[('auto', 'Auto-Approved (Rule Match)'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='auto', max_length=20)),
                ('approved_by', models.CharField(blank=True, default='', max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True, default='')),
                ('is_bulk', models.BooleanField(default=False, help_text='Flag for bulk/grouped items')),
                ('bulk_group_ref', models.CharField(blank=True, default='', help_text='Reference grouping bulk items together', max_length=100)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capitalization_prompts', to='stores.inventoryitem')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capitalization_prompts', to='stores.s2transaction')),
            ],
            options={
                'verbose_name': 'Capitalization Prompt',
                'verbose_name_plural': 'Capitalization Prompts',
                'db_table': 'stores_capitalization_prompt',
                'ordering': ['-createdAt'],
            },
        ),
    ]
