# Generated by Django 5.2.13 on 2026-05-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0032_phase5_depreciation_engine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depreciationschedule',
            name='depreciation_run',
        ),
        migrations.AlterUniqueTogether(
            name='depreciationschedule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='depreciationschedule',
            name='asset',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='delivery_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='expected_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='procurement_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='quotation_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vat_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vote_head',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='account',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='requisition',
            name='approval_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requisition',
            name='dept_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='requisition',
            name='priority',
            field=models.CharField(blank=True, default='normal', max_length=30),
        ),
        migrations.AddField(
            model_name='requisition',
            name='req_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='requisition',
            name='required_by',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='vote_head',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='approved_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='in_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='issued_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='req_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='DepreciationRun',
        ),
        migrations.DeleteModel(
            name='DepreciationSchedule',
        ),
    ]
