# Generated by Django 5.2.13 on 2026-05-07 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0033_remove_depreciationschedule_depreciation_run_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkCreationJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bulk_group_ref', models.CharField(max_length=100)),
                ('options', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bulk Creation Job',
                'verbose_name_plural': 'Bulk Creation Jobs',
                'db_table': 'stores_bulk_creation_job',
            },
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='depreciation_start_date',
            field=models.DateField(blank=True, help_text='Date when depreciation begins', null=True),
        ),
        migrations.CreateModel(
            name='AssetDisposalRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('disposed_qty', models.IntegerField(default=0)),
                ('disposal_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('disposal_status', models.CharField(blank=True, default='', max_length=50)),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('approval_status', models.CharField(default='pending', help_text='pending|approved|rejected', max_length=20)),
                ('committee_reference', models.CharField(blank=True, default='', max_length=255)),
                ('proceeds', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('write_off_posted', models.BooleanField(default=False)),
                ('approved_by', models.CharField(blank=True, default='', max_length=255)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposals', to='stores.fixedasset')),
            ],
            options={
                'verbose_name': 'Asset Disposal',
                'verbose_name_plural': 'Asset Disposals',
                'db_table': 'stores_asset_disposal',
            },
        ),
    ]
