# Generated by Django 5.2.13 on 2026-05-07 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0034_bulkcreationjob_fixedasset_depreciation_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryledger',
            name='committedQty',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RequisitionApproval',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('approver', models.CharField(max_length=255)),
                ('level', models.IntegerField(default=1)),
                ('decision', models.CharField(max_length=30)),
                ('comments', models.TextField(blank=True, default='')),
                ('items', models.JSONField(default=list)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='stores.requisition')),
            ],
        ),
    ]
