# Generated by Django 5.2.13 on 2026-05-07 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0035_inventoryledger_committedqty_requisitionapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='createdBy',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='requisition',
            name='updatedBy',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='RequisitionStatusLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('previous_status', models.CharField(max_length=100)),
                ('new_status', models.CharField(max_length=100)),
                ('changed_by', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True, default='')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='stores.requisition')),
            ],
        ),
    ]
