# Generated by Django 5.2.13 on 2026-05-07 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0036_requisition_createdby_requisition_updatedby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuehistory',
            name='requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='stores.requisition'),
        ),
    ]
