# Generated by Copilot assistant - basic migration to add Item and constraints
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


def add_inventoryitem_constraint(apps, schema_editor):
    # constraint already declared on model; for sqlite this is a no-op fallback
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0038_merge_0028_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('type', models.CharField(default='consumable', max_length=20)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('base_unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'db_table': 'stores_item'},
        ),
        migrations.RunPython(add_inventoryitem_constraint, reverse_code=migrations.RunPython.noop),
    ]
