# Generated by Django 5.2.13 on 2026-05-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0039_schema_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalizationPolicy',
            fields=[
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('updated_by', models.CharField(blank=True, default='', max_length=255)),
                ('approved_by', models.CharField(blank=True, default='', max_length=255)),
                ('locked', models.BooleanField(default=False)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('capitalization_threshold', models.DecimalField(decimal_places=2, default=50000, max_digits=12)),
                ('bulk_materiality_threshold', models.DecimalField(decimal_places=2, default=100000, max_digits=12)),
                ('min_useful_life_years', models.PositiveSmallIntegerField(default=2)),
                ('default_residual_value_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('depreciation_start_rule', models.CharField(default='deployed', max_length=100)),
                ('asset_classes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stores_capitalizationpolicy',
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='approved_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='updated_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='approved_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='updated_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('consumable', 'Consumable'), ('expendable', 'Expendable'), ('permanent', 'Permanent'), ('fixed_asset', 'Fixed Asset')], default='consumable', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('category_type__in', ['consumable', 'expendable', 'permanent', 'fixed_asset'])), name='stores_inventoryitem_valid_type'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['consumable', 'expendable', 'permanent', 'fixed_asset'])), name='stores_item_valid_type'),
        ),
    ]
