# Generated by Django 5.2.13 on 2026-05-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0041_storeledger_fixedasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeledger',
            name='approved_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='storeledger',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='storeledger',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeledger',
            name='updated_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='storeledger',
            name='ledger_type',
            field=models.CharField(choices=[('s1_consumable', 'S1 - Consumable'), ('s2_permanent_expendable', 'S2 - Permanent/Expendable')], default='s1_consumable', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='storeledger',
            constraint=models.CheckConstraint(condition=models.Q(('ledger_type__in', ['s1_consumable', 's2_permanent_expendable'])), name='stores_storeledger_valid_type'),
        ),
    ]
