# Generated by Django 5.2.13 on 2026-05-14 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0042_storeledger_approved_by_storeledger_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='approved_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='locked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='updated_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='OverrideLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('original_recommendation', models.CharField(blank=True, default='', max_length=100)),
                ('final_decision', models.CharField(blank=True, default='', max_length=100)),
                ('reason', models.TextField(blank=True, default='')),
                ('override_by', models.CharField(blank=True, default='', max_length=255)),
                ('approved_by', models.CharField(blank=True, default='', max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='override_logs', to='stores.capitalizationprompt')),
            ],
            options={
                'db_table': 'stores_override_log',
            },
        ),
    ]
