# Generated by Django 5.2.13 on 2026-05-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0043_fixedasset_approved_by_fixedasset_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='issued_s13',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
