# Generated by Django 5.2.13 on 2026-05-14 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0044_requisition_issued_s13'),
    ]

    operations = [
        migrations.AddField(
            model_name='lsorecord',
            name='account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lsorecord',
            name='authorized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lsorecord',
            name='authorized_by_bursar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lsorecord',
            name='completed_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lsorecord',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lsorecord',
            name='completion_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lsorecord',
            name='completion_verified_by_committee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lsorecord',
            name='cost_lines',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='lsorecord',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lsorecord',
            name='generated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lsorecord',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lsorecord',
            name='prepared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lsorecord',
            name='prepared_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lsorecord',
            name='principal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lsorecord',
            name='print_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lsorecord',
            name='procurement_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lsorecord',
            name='provider_ack_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lsorecord',
            name='provider_ack_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lsorecord',
            name='provider_ack_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lsorecord',
            name='provider_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lsorecord',
            name='provider_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lsorecord',
            name='provider_kra_pin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lsorecord',
            name='provider_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lsorecord',
            name='provider_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lsorecord',
            name='quotation_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lsorecord',
            name='service_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lsorecord',
            name='service_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lsorecord',
            name='service_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lsorecord',
            name='service_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lsorecord',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='lsorecord',
            name='system_ref_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lsorecord',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='lsorecord',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='lsorecord',
            name='vote_head',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lsorecord',
            name='status',
            field=models.CharField(default='Draft', max_length=50),
        ),
        migrations.CreateModel(
            name='ServiceVerification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('verifier', models.CharField(max_length=255)),
                ('verifier_role', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('lso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='stores.lsorecord')),
            ],
            options={
                'db_table': 'stores_service_verification',
            },
        ),
    ]
